# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export EDITOR=vim

MNAZIMS_DEFAULT_COLOR="[00m"
MNAZIMS_GRAY_COLOR="[37m"
MNAZIMS_PINK_COLOR="[35m"
MNAZIMS_GREEN_COLOR="[32m"
MNAZIMS_ORANGE_COLOR="[33m"
MNAZIMS_RED_COLOR="[31m"
if [ `id -u` == '0' ]; then
  MNAZIMS_USER_COLOR=$MNAZIMS_RED_COLOR
else
  MNAZIMS_USER_COLOR=$MNAZIMS_PINK_COLOR
fi
MNAZIMS_VCPROMPT_EXECUTABLE=~/bin/vcprompt

mitsuhikos_vcprompt() {
  $MNAZIMS_VCPROMPT_EXECUTABLE -f $' on \033[34m%n\033[00m:\033[00m%[unknown]b\033[32m%m%u'
}

export MNAZIMS_BASEPROMPT='\n\e${MNAZIMS_USER_COLOR}\u \
\e${MNAZIMS_GRAY_COLOR}at \e${MNAZIMS_ORANGE_COLOR}\h \
\e${MNAZIMS_GRAY_COLOR}in \e${MNAZIMS_GREEN_COLOR}\w\
\e${MNAZIMS_GRAY_COLOR}$(mitsuhikos_vcprompt)\e${MNAZIMS_DEFAULT_COLOR}'
export PS1="${MNAZIMS_BASEPROMPT}
$ "

export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
export LC_CTYPE=en_US.utf-8
export PATH=/usr/local/bin:$PATH
export IGNOREEOF=1
export PYTHONDONTWRITEBYTECODE=1
export LESS=FRSX

# virtualenvwrapper and pip
if [ `id -u` != '0' ]; then
  export VIRTUALENV_USE_DISTRIBUTE=1
  export WORKON_HOME=$HOME/Work/python/envs
  source /usr/local/bin/virtualenvwrapper.sh
  export PIP_VIRTUALENV_BASE=$WORKON_HOME
  export PIP_RESPECT_VIRTUALENV=true
fi

#alias git=hub
alias rvim="gvim --remote-silent"
shopt -s histappend

. ~/.dotfiles/git-completion.bash
